### Create a new Patient Entity
POST http://localhost:4004/patients
Content-Type: application/json

{
  "name": "YoussefAzozz",
  "email": "azozz@yahoo.com",
  "password": "mancity1011",
  "address": "Giza Al Haramdas",
  "dateOfBirth": "2001-04-15",
  "registeredDate": "2025-08-28"
}

###