### Get Request to get All Patients
GET http://localhost:4004/api/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhem96enR0YW1hbUB5YWhvby5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc2MjU2NDkyNywiZXhwIjoxNzYyNjAwOTI3fQ.lNeKbrNqnQHQyIyHxHV2zzlr-M-TLJ3FcsXVv7Lp_6U

###