### Update Patient Object
PUT http://localhost:4004/api/patients/update-patient/196fe387-9e65-4278-9ced-eda5e9a18f5f
Content-Type: application/json

{
  "name": "Azozz",
  "email": "azozzz@gmail.com",
  "address": "Giza Al Haram",
  "dateOfBirth": "2001-04-18"
}

###